version: '3'

services:
  token_server:
    build: .
    container_name: arcanelink_token_server
    restart: unless-stopped
    command: 'uvicorn src.app:app --host 0.0.0.0 --port 80'
    ports:
      - '80:80'
    volumes:
      - ./src:/home/user/src:ro

  redis:
      image: redis:7-alpine
      container_name: arcanelink_token_db
      restart: unless-stopped
      command: redis-server --save 30 1 --loglevel warning
      volumes:
        - redis_data:/data

volumes:
  redis_data:
    driver: local
